# Generated by Django 2.1.2 on 2018-10-03 22:25

from django.db import migrations, models

from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('mutings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.utcnow()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='initial_action',
            field=models.BooleanField(default=False),
        ),
    ]
