# Generated by Django 2.1.2 on 2018-10-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutings', '0002_auto_20181003_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='to_user',
            new_name='user',
        ),
    ]
